[[repos]]
repo = "builtin"
hooks = [
    { id = "check-added-large-files" },
    { id = "check-toml" },
    { id = "check-yaml" },
    { id = "end-of-file-fixer" },
    { id = "mixed-line-ending" },
    { id = "trailing-whitespace" }
]

[[repos]]
repo = "https://github.com/charliermarsh/ruff-pre-commit"
rev = "v0.15.18"
hooks = [
    { id = "ruff-format" },
    { id = "ruff-check" }
]
